<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class BankListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('bank_lists')->truncate();

    	DB::table('bank_lists')->insert([
		    [
		        "name" => "AB Bank Ltd.",
		        "short_code" => "ABL",
		        "type" => "Private Commercial Banks",
		        "founded" => "April 2, 1982",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.abbl.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Agrani Bank",
		        "short_code" => "ABL",
		        "type" => "State Owned Commercial Banks",
		        "founded" => "26 March 1972",
		         "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.agranibank.org",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Al-Arafah Islami Bank Ltd.",
		        "short_code" => "AAIBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1995",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "al-arafahbank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Ansar VDP Unnayan Bank",
		        "short_code" => "AVUB",
		        "type" => "Non-scheduled banks",
		        "founded" => "Dhaka, Bangladesh",
		         "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "ansarvdpbank.gov.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "BASIC Bank",
		        "short_code" => "BBL",
		        "type" => "State Owned Commercial Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "http://www.basicbanklimited.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "BRAC Bank Ltd.",
		        "short_code" => "BBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "4 July 2001",
		        "founder" => "",
		        "headquarter" => "220/B Gulshan Tejgaon Link Road, Dhaka 1208 Dhaka, Bangladesh",
		        "website" => "www.bracbank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Bangladesh Commerce Bank Ltd.",
		        "short_code" => "BCBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Bangladesh Development Bank",
		        "short_code" => "BDB",
		        "type" => "State Owned Commercial Banks",
		        "founded" => "16 November 2009",
		        "founder" => "",
		        "headquarter" => "",
		        "website" => "www.bdbl.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Bangladesh Krishi Bank",
		        "short_code" => "BKB",
		        "type" => "Specialized Banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "http://www.krishibank.org.bd/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Bank Al-Falah",
		        "short_code" => "BAFL",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "June 21, 1997",
		        "founder" => "",
		        "headquarter" => "Karachi, Pakistan",
		        "website" => "www.bankalfalah.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Bank Asia Ltd.",
		        "short_code" => "BAL",
		        "type" => "Private Commercial Banks",
		        "founded" => "27 November 1999",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "Bank Asia Limited",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "CITI Bank NA",
		        "short_code" => "CITIBNA",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "June 16, 1812",
		        "founder" => "",
		        "headquarter" => "New York City, New York",
		        "website" => "citi.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Commercial Bank of Ceylon",
		        "short_code" => "CBOC",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "1920",
		        "founder" => "",
		        "headquarter" => "Colombo, Sri Lanka",
		        "website" => "",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Community Bank Bangladesh Limited",
		        "short_code" => "CBBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "2019",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.communitybankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Dhaka Bank Ltd.",
		        "short_code" => "DBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "July 5, 1995",
		        "founder" => "Mirza Abbas",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "dhakabankltd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Dutch Bangla Bank Ltd.",
		        "short_code" => "DBBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1995",
		        "founder" => "",
		        "headquarter" => "Motijheel, Dhaka, Bangladesh",
		        "website" => "dutchbanglabank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "EXIM Bank Ltd.",
		        "short_code" => "EXIM",
		        "type" => "Private Commercial Banks",
		        "founded" => "3 August 1999",
		        "founder" => "Late Mr. Shahjahan Kabir",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.eximbankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Eastern Bank Ltd.",
		        "short_code" => "EBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "August 8, 1992",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "ebl.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "First Security Islami Bank Ltd.",
		        "short_code" => "FSIBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "25 October 1999",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "fsiblbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Global Islamic Bank Ltd.",
		        "short_code" => "GIBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "",
		        "website" => "https://www.globalislamibankbd.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Grameen Bank",
		        "short_code" => "GB",
		        "type" => "Non-scheduled banks",
		        "founded" => "October 1983 (1983-10)",
		        "founder" => "Muhammad Yunus",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "grameen.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "HSBC",
		        "short_code" => "HSBC",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "3 March 1865",
		        "founder" => "Sir Thomas Sutherland",
		        "headquarter" => "HSBC Main Building, Central, Hong Kong",
		        "website" => "www.hsbc.com.hk",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Habib Bank Ltd.",
		        "short_code" => "HBL",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "25 August 1940",
		        "founder" => "Mohammed Ali Habib[2]  Dawood Habib[2]",
		        "headquarter" => "Habib Bank Plaza, Karachi, Pakistan",
		        "website" => "www.hbl.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "ICB Islamic Bank",
		        "short_code" => "IIBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1987",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "https://www.icbislamic-bd.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "IFIC Bank Ltd.",
		        "short_code" => "IBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1976",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.ificbankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Islami Bank Bangladesh Ltd.",
		        "short_code" => "IBBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "13 March 1983",
		        "founder" => "",
		        "headquarter" => "Islami Bank Tower 40, Dilkusha C/A, Dhaka - 1000, Bangladesh",
		        "website" => "islamibankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Jamuna Bank Ltd.",
		        "short_code" => "JBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "2001",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.jamunabankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Janata Bank",
		        "short_code" => "JBL",
		        "type" => "State Owned Commercial Banks",
		        "founded" => "1971",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "http://www.jb.com.bd/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Jubilee Bank",
		        "short_code" => "JB",
		        "type" => "Non-scheduled banks",
		        "founded" => "Kushtia, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Kushtia, Bangladesh",
		        "website" => "jubileebank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Karmashangosthan Bank",
		        "short_code" => "KB",
		        "type" => "Non-scheduled banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "Karmasangsthan Bank",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Meghna Bank Ltd.",
		        "short_code" => "MBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "21 April 2013",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "http://www.meghnabank.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Mercantile Bank Ltd.",
		        "short_code" => "MBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1999",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.mblbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Midland Bank Ltd.",
		        "short_code" => "MBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "June 20, 2013",
		        "founder" => "",
		        "headquarter" => "Gulshan Avenue, Gulshan-2, Dhaka",
		        "website" => "https://www.midlandbankbd.net/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Modhumoti Bank Ltd.",
		        "short_code" => "MBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1999",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "https://www.modhumotibankltd.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Mutual Trust Bank Ltd.",
		        "short_code" => "MTBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "mutualtrustbank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "NCC Bank Ltd.",
		        "short_code" => "NCCBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1985",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "NRB Bank Ltd.",
		        "short_code" => "NBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "2013",
		        "founder" => "Iqbal Ahmed (OBE)",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.nrbbankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "NRB Commercial Bank Ltd.",
		        "short_code" => "NCBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "02 April 2013",
		        "founder" => "",
		        "headquarter" => "",
		        "website" => "https://www.nrbcommercialbank.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "National Bank Ltd.",
		        "short_code" => "NBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.nblbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "National Bank of Pakistan",
		        "short_code" => "NBOP",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "1949",
		        "founder" => "",
		        "headquarter" => "Karachi Pakistan",
		        "website" => "www.nbp.com.pk",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "One Bank Ltd.",
		        "short_code" => "OBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Padma Bank Ltd.",
		        "short_code" => "PBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "2013",
		        "founder" => "",
		        "headquarter" => "Gulshan-1, Dhaka, Bangladesh",
		        "website" => "www.padmabankbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Palli Sanchay Bank",
		        "short_code" => "PSB",
		        "type" => "Non-scheduled banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.pallisanchaybank.gov.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Premier Bank Ltd.",
		        "short_code" => "PBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1999",
		        "founder" => "",
		        "headquarter" => "42 Kemal Ataturk Avenue, Banani, Dhaka, Bangladesh",
		        "website" => "www.premierbankltd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Prime Bank Ltd.",
		        "short_code" => "PBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1995",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "primebank.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Pubali Bank Ltd.",
		        "short_code" => "PBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1959",
		        "founder" => "",
		        "headquarter" => "26 Dilkusha Commercial Area Dhaka, Bangladesh",
		        "website" => "http://www.pubalibangla.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Rajshahi Krishi Unnayan Bank",
		        "short_code" => "RKUB",
		        "type" => "Specialized Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "",
		        "website" => "http://www.rakub.org.bd/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Rupali Bank",
		        "short_code" => "RBL",
		        "type" => "State Owned Commercial Banks",
		        "founded" => "1972",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "rupalibank.org",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "SBAC Bank Ltd.",
		        "short_code" => "SBAC",
		        "type" => "Private Commercial Banks",
		        "founded" => "2013",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Shahjalal Islami Bank Ltd.",
		        "short_code" => "SIBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "sjiblbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Shimanto Bank Ltd.",
		        "short_code" => "SBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "http://www.shimantobank.com/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Social Islami Bank Ltd.",
		        "short_code" => "SIBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "90/1, City Center, Motijheel, Dhaka-1000, Bangladesh",
		        "website" => "siblbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Sonali Bank",
		        "short_code" => "SBL",
		        "type" => "State Owned Commercial Banks",
		        "founded" => "1972",
		        "founder" => "",
		        "headquarter" => "Motijheel, Dhaka, Bangladesh",
		        "website" => "http://sonalibank.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Southeast Bank Ltd.",
		        "short_code" => "SBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1995",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.southeastbank.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Standard Bank Ltd.",
		        "short_code" => "SBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "Dhaka, Bangladesh",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "Standard Bank Limited",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Standard Chartered Bank",
		        "short_code" => "SCB",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "29 December 1853",
		        "founder" => "James Wilson",
		        "headquarter" => "London, England, UK",
		        "website" => "www.sc.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "State Bank of India",
		        "short_code" => "SBOI",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "2 June 1806",
		        "founder" => "",
		        "headquarter" => "State Bank Bhawan, M.C. Road, Nariman Point, Mumbai, Maharashtra, India",
		        "website" => "bank.sbi",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "The City Bank Ltd.",
		        "short_code" => "TCBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "28 March 1983",
		        "founder" => "Mr. Monowar Ali, Mr. Ibrahim Mia (Late), Mr. Abdul Hadi (Late), Mr. M.A. Hashem (Late), Mr. Anwar Hossain, Mr. Abdul Barik Choudhury (Late), Mr. Deen Mohammad, Mr. A.B.M. Feroz, Mr. Md. Ali Hossain, Mr. Azizul Haque Chowdhury, Mr. N.A. Chowdhury (Late)",
		        "headquarter" => "136 Gulshan Avenue, Circle 2, Gulshan, Dhaka, Bangladesh",
		        "website" => "thecitybank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Trust Bank Ltd.",
		        "short_code" => "TBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "1999",
		        "founder" => "",
		        "headquarter" => "Shadhinota Tower, Bir Srestha Shahid Jahangir Gate, Dhaka Cantonment, Dhaka, Bangladesh",
		        "website" => "www.tblbd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Union Bank Ltd.",
		        "short_code" => "UBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "",
		        "founder" => "",
		        "headquarter" => "",
		        "website" => "https://www.unionbank.com.bd/",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "United Commercial Bank Ltd.",
		        "short_code" => "UCBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "",
		        "founder" => "Akhtaruzzaman Chowdhury Babu",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.ucb.com.bd",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Uttara Bank Ltd.",
		        "short_code" => "UBL",
		        "type" => "Private Commercial Banks",
		        "founded" => "Dhaka, Bangladesh (1965)",
		        "founder" => "",
		        "headquarter" => "Dhaka, Bangladesh",
		        "website" => "www.uttarabank-bd.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ],
		    [
		        "name" => "Woori Bank Ltd.",
		        "short_code" => "WBL",
		        "type" => "Foreign Commercial Banks",
		        "founded" => "30 January 1899",
		        "founder" => "",
		        "headquarter" => "Hoehyeon-dong, Jung-gu, Seoul, South Korea",
		        "website" => "www.wooribank.com",
		        'created_at' => Carbon::now(),
	            'updated_at' => Carbon::now(),
		    ]
		]);
	}
}
